index.htmlにcss追加
Dai-H15/django-test-exercise pull request #21
Opened 2023-07-22 09:14 UTC by s1f10220078

index.htmlにcss追加

2023-07-22 14:11 UTC, Dai-H15 approved these changes
おｋ

2023-07-22 15:01 UTC, Dai-H15 requested changes
リモートからプルしてみたんですけど、タスク追加時にエラーになります。
mainブランチからプルしてみたりってしました？

2023-07-22 15:09 UTC, Dai-H15 commented
いちどPullした後の動作が問題ないかも確認してほしいです！

2023-07-22 20:45 UTC, s1f10220078 commented
これどう？

2023-07-23 05:25 UTC, Dai-H15 approved these changes
おｋ

2023-07-23 05:57 UTC, s1f10220269 approved these changes
ok

2023-07-23 21:58 UTC, s1f102200907-Mao approved these changes
OK

2023-07-24 01:55 UTC, merged